### ISSUE TITLE
i cannot see anything on the export panel

### ISSUE THREAD

**Issue by kangpyo** [Amudtogal/blenderMotionExport#4]
![Picture2](https://user-images.githubusercontent.com/53060924/106388187-62053d00-63ab-11eb-8fc6-cac0862f4530.png)

Hi, this is fantastic code. i like it if this works well. 
i installed the code and create the new panel. but I don;t know why I cannot see anything in the export panel after adjusting the tracking?

**Comment by Amudtogal** [comment]
That is interesting, yes...

Could you try installing the Addon via the Addon Manager in the `User Preferences`?
There is an install button, you select the python file and that should set everything up.

**Comment by Amudtogal** [comment]
If that won't help, could you look at the output of the system console (so if you are on Linux/Mac, run Blender from the terminal; if on Windows, check `Window` -> `Toggle System Console`).
If there are any errors there, post the output here :)

**Comment by kangpyo** [comment]
thanks for your reply. 
Actually, i discovered that version 1.2.2 works for me. 

here is the code what I found 
https://raw.githubusercontent.com/Amudtogal/blenderMotionExport/1.2.2/motionExportAddon.py

but not sure if this is the same thing and magically work.

**Comment by Amudtogal** [comment]
Excellent! This is the version for newer Blender!

Let me know how it works for you!

**Comment by hoyelow** [comment]
Thanks a lot, the ver1.1 can't work on Blender2.91, but this ver1.2.2 can work, Thank you very much.
