### ISSUE TITLE
export track data as csv file

### ISSUE THREAD

**Issue by hoyelow** [Amudtogal/blenderMotionExport#5]

**Comment by Amudtogal** [comment]
Well this ran quickly, I didn't even get to see what the problem was, but good luck!

Let me know, how it has been of use to you!

**Comment by hoyelow** [comment]
Thanks a lot. The problem had been solved : ). The new version 1.2.2 can
work for Blender v2.91.
It's a very useful tool for our research project, we track the eyelid's
movement in the different light intensities to explore how light affects
human's sleep.
  --
Yanlong HOU
CRNL 69500 France

Simon Reichel <notifications@github.com> 于2021年2月18日周四 下午5:10写道：

**Comment by Amudtogal** [comment]
Ah great! Looking forward to seeing the results. Happy researching!
