### ISSUE TITLE
No items under export in the clip editor

### ISSUE THREAD

**Issue by alfredtayloraero** [Amudtogal/blenderMotionExport#6]
This may be an issue with the newer LTS blender version I'm running (2.93.1) but under the export tab in tracking and export there are no export directory or frame selection options.

**Comment by Amudtogal** [comment]
Hey,
I just checked with the recent LTS 2.93.8 (fresh download), and I have all the options available.
Have you downloaded the most recent addon version (see the [releases](https://github.com/Amudtogal/blenderMotionExport/releases) page)?

Cheers,
Amudtogal
